### ISSUE TITLE
Mac OS 10.10.5 LoadError compass

### ISSUE THREAD

**Issue by nooperpudd** [scout-app/scout-app#223]
Scout : 0.7.1
ruby: 
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]

sass:  
sass (3.4.19)
compass (1.0.3)
compass-core (1.0.3)
compass-import-once (1.0.5)

```
# used for compass sass
require 'compass/import-once/activate'
# Require any additional compass plugins here.

# Set this to the root of your project when deployed:
http_path = "/"
css_dir = "css"
sass_dir = "sass"
images_dir = "img"
javascripts_dir = "js"
preferred_syntax = :scss

# You can select your preferred output style here (can be overridden via the command line):
# output_style = :expanded or :nested or :compact or :compressed

# To enable relative paths to assets via compass helper functions. Uncomment:
# relative_assets = true

# To disable debugging comments that display the original location of your selectors. Uncomment:
# line_comments = false

# If you prefer the indented syntax, you might want to regenerate this
# project again passing --syntax sass, or you can uncomment this:

# and then run:
# sass-convert -R --from scss --to sass sass scss && rm -rf sass && mv scss sass


```

```
LoadError on line 1038 of org/jruby/RubyKernel.java: no such file to load -- compass/import-once/activate
/Applications/Scout.app/Contents/Resources/vendor/gems/gems/compass-0.12.2/lib/compass/configuration/data.rb:161:in `require' /Users/weichenwang/quantvc/web/quantvc/assets/config.rb:21:in `parse_string' org/jruby/RubyKernel.java:1088:in `eval' /Applications/Scout.app/Contents/Resources/vendor/gems/gems/compass-0.12.2/lib/compass/configuration/serialization.rb:24:in `parse_string' /Applications/Scout.app/Contents/Resources/vendor/gems/gems/compass-0.12.2/lib/compass/configuration/serialization.rb:15:in `_parse' org/jruby/RubyIO.java:1111:in `open' org/jruby/RubyKernel.java:298:in `open' /Applications/Scout.app/Contents/Resources/vendor/gems/gems/compass-0.12.2/lib/compass/configuration/serialization.rb:14:in `_parse' /Applications/Scout.app/Contents/Resources/vendor/gems/gems/compass-0.12.2/lib/compass/configuration/file_data.rb:7:in `new_from_file' /Applications/Scout.app/Contents/Resources/vendor/gems/gems/compass-0.12.2/lib/compass/configuration/inheritance.rb:204:in `with_defaults' /Applications/Scout.app/Contents/Resources/vendor/gems/gems/compass-0.12.2/lib/compass/configuration/file_data.rb:6:in `new_from_file' /Applications/Scout.app/Contents/Resources/vendor/gems/gems/compass-0.12.2/lib/compass/configuration/helpers.rb:42:in `configuration_for' /Applications/Scout.app/Contents/Resources/vendor/gems/gems/compass-0.12.2/lib/compass/configuration/helpers.rb:97:in `add_project_configuration' /Applications/Scout.app/Contents/Resources/vendor/gems/gems/compass-0.12.2/lib/compass/commands/project_base.rb:31:in `add_project_configuration' /Applications/Scout.app/Contents/Resources/vendor/gems/gems/compass-0.12.2/lib/compass/commands/project_base.rb:25:in `configure!' /Applications/Scout.app/Contents/Resources/vendor/gems/gems/compass-0.12.2/lib/compass/commands/project_base.rb:15:in `initialize' /Applications/Scout.app/Contents/Resources/vendor/gems/gems/compass-0.12.2/lib/compass/commands/update_project.rb:37:in `initialize' /Applications/Scout.app/Contents/Resources/vendor/gems/gems/compass-0.12.2/lib/compass/exec/sub_command_ui.rb:42:in `perform!' /Applications/Scout.app/Contents/Resources/vendor/gems/gems/compass-0.12.2/lib/compass/exec/sub_command_ui.rb:15:in `run!' /Applications/Scout.app/Contents/Resources/bin/compass:12:in `(root)'
```

**Comment by TheJaredWilcurt** [comment]
Issue resolved. Closing this ticket.

* [Scout-App 2](http://Scout-App.io)
