### ISSUE TITLE
scout java error

### ISSUE THREAD

**Issue by rrahulgupta** [scout-app/scout-app#321]
I need to start work on sass. but after all the installation process i get bellow message in scout. I thought it may need java but java is already installed in my system. how to fix and how it work for scss compiling.

**java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: Could not locate stub library in jar file. Tried [jni/i386-Windows/jffi-?.?.dll, /jni/i386-Windows/jffi-?.?.dll] 
at com.kenai.jffi.Foreign$InValidInstanceHolder.getForeign(Foreign.java:90) at com.kenai.jffi.Foreign.getInstance(Foreign.java:95) at com.kenai.jffi.Library.openLibrary(Library.java:151) at com.kenai.jffi.Library.getCachedInstance(Library.java:125)
at com.kenai.jaffl.provider.jffi.Library.loadNativeLibraries(Library.java:66) at com.kenai.jaffl.provider.jffi.Library.getNativeLibraries(Library.java:56) at com.kenai.jaffl.provider.jffi.Library.getSymbolAddress(Library.java:35) at com.kenai.jaffl.provider.jffi.Library.findSymbolAddress(Library.java:45) at com.kenai.jaffl.provider.jffi.AsmLibraryLoader.generateInterfaceImpl(AsmLibraryLoader.java:188) at com.kenai.jaffl.provider.jffi.AsmLibraryLoader.loadLibrary(AsmLibraryLoader.java:110) at com.kenai.jaffl.provider.jffi.Provider.loadLibrary(Provider.java:31) at com.kenai.jaffl.provider.jffi.Provider.loadLibrary(Provider.java:25) at com.kenai.jaffl.Library.loadLibrary(Library.java:76) at org.jruby.ext.posix.POSIXFactory$WindowsLibCProvider$SingletonHolder.(POSIXFactory.java:130) at org.jruby.ext.posix.POSIXFactory$WindowsLibCProvider.getLibC(POSIXFactory.java:134) at org.jruby.ext.posix.BaseNativePOSIX.(BaseNativePOSIX.java:30) at org.jruby.ext.posix.WindowsPOSIX.(WindowsPOSIX.java:119) at org.jruby.ext.posix.POSIXFactory.loadWindowsPOSIX(POSIXFactory.java:90) at org.jruby.ext.posix.POSIXFactory.loadPOSIX(POSIXFactory.java:39) at org.jruby.ext.posix.LazyPOSIX.loadPOSIX(LazyPOSIX.java:29) at org.jruby.ext.posix.LazyPOSIX.posix(LazyPOSIX.java:25) at org.jruby.ext.posix.LazyPOSIX.setenv(LazyPOSIX.java:263) at org.jruby.RubyGlobal$StringOnlyRubyHash.case_aware_op_aset(RubyGlobal.java:175) at org.jruby.RubyGlobal$CaseInsensitiveStringOnlyRubyHash.op_aset(RubyGlobal.java:87) at org.jruby.RubyHash$i$2$0$op_aset.call(RubyHash$i$2$0$op_aset.gen:65535) at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:332) at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:203) at org.jruby.javasupport.util.RuntimeHelpers.doAttrAsgn(RuntimeHelpers.java:96) at C_3a_.scout_minus_app_minus_0_dot_7_dot_1_minus_win.Scout_minus_Installer.bin.compass.__file__(C:\scout-app-0.7.1-win\Scout-Installer\bin\compass:1) at C_3a_.scout_minus_app_minus_0_dot_7_dot_1_minus_win.Scout_minus_Installer.bin.compass.load(C:\scout-app-0.7.1-win\Scout-Installer\bin\compass) at org.jruby.Ruby.runScript(Ruby.java:671) at org.jruby.Ruby.runNormally(Ruby.java:575) at org.jruby.Ruby.runFromMain(Ruby.java:424) at org.jruby.Main.doRunFromMain(Main.java:278) at org.jruby.Main.internalRun(Main.java:198) at org.jruby.Main.run(Main.java:164) at org.jruby.Main.run(Main.java:148) at org.jruby.Main.main(Main.java:128) Caused by: java.lang.UnsatisfiedLinkError: Could not locate stub library in jar file. Tried [jni/i386-Windows/jffi-?.?.dll, /jni/i386-Windows/jffi-?.?.dll] 
at com.kenai.jffi.Init.getStubLibraryStream(Init.java:201) at com.kenai.jffi.Init.loadFromJar(Init.java:136) at com.kenai.jffi.Init.load(Init.java:78) at com.kenai.jffi.Foreign$InstanceHolder.getInstanceHolder(Foreign.java:49) at com.kenai.jffi.Foreign$InstanceHolder.(Foreign.java:45) at com.kenai.jffi.Foreign.getInstance(Foreign.java:95) at com.kenai.jffi.Internals.getErrnoSaveFunction(Internals.java:44) at com.kenai.jaffl.provider.jffi.StubCompiler.getErrnoSaveFunction(StubCompiler.java:68) at com.kenai.jaffl.provider.jffi.StubCompiler.(StubCompiler.java:18) at com.kenai.jaffl.provider.jffi.AsmLibraryLoader.generateInterfaceImpl(AsmLibraryLoader.java:146) ... 29 more Foreign.java:90:in `getForeign': java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: Could not locate stub library in jar file. Tried [jni/i386-Windows/jffi-?.?.dll, /jni/i386-Windows/jffi-?.?.dll]
from Foreign.java:95:in `getInstance' from Library.java:151:in `openLibrary' from Library.java:125:in `getCachedInstance' from Library.java:66:in `loadNativeLibraries' from Library.java:56:in `getNativeLibraries' from Library.java:35:in `getSymbolAddress' from Library.java:45:in `findSymbolAddress' from DefaultInvokerFactory.java:51:in `createInvoker' from Library.java:27:in `getInvoker' from NativeInvocationHandler.java:90:in `createInvoker' from NativeInvocationHandler.java:74:in `getInvoker' from NativeInvocationHandler.java:110:in `invoke' from null:-1:in `SetEnvironmentVariableW' from WindowsPOSIX.java:298:in `setenv' from LazyPOSIX.java:263:in `setenv' from RubyGlobal.java:175:in `case_aware_op_aset' from RubyGlobal.java:87:in `op_aset' from RubyHash$i$2$0$op_aset.gen:65535:in `call' from CachingCallSite.java:332:in `cacheAndCall' from CachingCallSite.java:203:in `call' from RuntimeHelpers.java:96:in `doAttrAsgn' from C:\scout-app-0.7.1-win\Scout-Installer\bin\compass:1:in `__file__' from C:\scout-app-0.7.1-win\Scout-Installer\bin\compass:-1:in `load' from Ruby.java:671:in `runScript' from Ruby.java:575:in `runNormally' from Ruby.java:424:in `runFromMain' from Main.java:278:in `doRunFromMain' from Main.java:198:in `internalRun' from Main.java:164:in `run' from Main.java:148:in `run' from Main.java:128:in `main' Caused by: Init.java:201:in `getStubLibraryStream': java.lang.UnsatisfiedLinkError: Could not locate stub library in jar file. Tried [jni/i386-Windows/jffi-?.?.dll, /jni/i386-Windows/jffi-?.?.dll]
from Init.java:136:in `loadFromJar' from Init.java:78:in `load' from Foreign.java:49:in `getInstanceHolder' from Foreign.java:45:in `' from Foreign.java:95:in `getInstance' from Internals.java:44:in `getErrnoSaveFunction' from StubCompiler.java:68:in `getErrnoSaveFunction' from StubCompiler.java:18:in `' from AsmLibraryLoader.java:146:in `generateInterfaceImpl' from AsmLibraryLoader.java:110:in `loadLibrary' from Provider.java:31:in `loadLibrary' from Provider.java:25:in `loadLibrary' from Library.java:76:in `loadLibrary' from POSIXFactory.java:130:in `' from POSIXFactory.java:134:in `getLibC' from BaseNativePOSIX.java:30:in `' from WindowsPOSIX.java:119:in `' from POSIXFactory.java:90:in `loadWindowsPOSIX' from POSIXFactory.java:39:in `loadPOSIX' from LazyPOSIX.java:29:in `loadPOSIX' from LazyPOSIX.java:25:in `posix' from LazyPOSIX.java:263:in `setenv' from RubyGlobal.java:175:in `case_aware_op_aset' from RubyGlobal.java:87:in `op_aset' from RubyHash$i$2$0$op_aset.gen:65535:in `call' from CachingCallSite.java:332:in `cacheAndCall' from CachingCallSite.java:203:in `call' from RuntimeHelpers.java:96:in `doAttrAsgn' from C:\scout-app-0.7.1-win\Scout-Installer\bin\compass:1:in `__file__' from C:\scout-app-0.7.1-win\Scout-Installer\bin\compass:-1:in `load' from Ruby.java:671:in `runScript' from Ruby.java:575:in `runNormally' from Ruby.java:424:in `runFromMain' from Main.java:278:in `doRunFromMain' from Main.java:198:in `internalRun' from Main.java:164:in `run' from Main.java:148:in `run' from Main.java:128:in `main'
Configuration**

**Comment by TheJaredWilcurt** [comment]
@rrahulgupta 

Scout-App 2 no longer relies on Java, Adobe Air, or Ruby.

You can download the latest version at

* http://Scout-App.io

If you want to use Scout-App Classic (2012), you will need to install either Java 6 or Java 7 and Adobe Air.

* http://Scout-App.io/classic

Unless you have a legacy project that uses Compass (no longer maintained), it is recommended you use the latest version of Scout-App, as no more updates for Scout-App Classic are planned.
