### ISSUE TITLE
Compass SpriteException error

### ISSUE THREAD

**Issue by davidosomething** [scout-app/scout-app#97]
upon starting the application:

```
Compass::SpriteException on line 84 of /Applications/Scout.app/Contents/Resources/vendor/gems/gems/compass-0.12.2/lib/compass/sprite_importer.rb: No files were found in the load path matching "icons/*.png". Your current load paths are: /Users/dotrakoun/Sites/openshift/main/php/content/themes/2013-davidosomething/img
/Applications/Scout.app/Contents/Resources/vendor/gems/gems/compass-0.12.2/lib/compass/sprite_importer.rb:89:in `sprite_names' /Applications/Scout.app/Contents/Resources/vendor/gems/gems/compass-0.12.2/lib/compass/sprite_importer.rb:111:in `content_for_images' /Applications/Scout.app/Contents/Resources/vendor/gems/gems/compass-0.12.2/lib/compass/sprite_importer.rb:105:in `sass_engine' /Applications/Scout.app/Contents/Resources/vendor/gems/gems/compass-0.12.2/lib/compass/sprite_importer.rb:24:in `find' /Applications/Scout.app/Contents/Resources/vendor/gems/gems/sass-3.2.1/lib/sass/tree/import_node.rb:51:in `import'
org/jruby/RubyArray.java:1603:in `each' /Applications/Scout.app/Contents/Resources/vendor/gems/gems/sass-3.2.1/lib/sass/tree/import_node.rb:50:in `import' /Applications/Scout.app/Contents/Resources/vendor/gems/gems/sass-3.2.1/lib/sass/tree/import_node.rb:25:in `imported_file' /Applications/Scout.app/Contents/Resources/vendor/gems/gems/sass-3.2.1/lib/sass/tree/import_node.rb:33:in `css_import?' /Applications/Scout.app/Contents/Resources/vendor/gems/gems/sass-3.2.1/lib/sass/plugin/staleness_checker.rb:170:in `compute_dependencies' /Applications/Scout.app/Contents/Resources/vendor/gems/gems/sass-3.2.1/lib/sass/tree/node.rb:151:in `each' /Applications/Scout.app/Contents/Resources/vendor/gems/gems/sass-3.2.1/lib/sass/tree/node.rb:150:in `each' /Applications/Scout.app/Contents/Resources/vendor/gems/gems/sass-3.2.1/lib/sass/tree/node.rb:151:in `each' org/jruby/RubyArray.java:1603:in `each' /Applications/Scout.app/Contents/Resources/vendor/gems/gems/sass-3.2.1/lib/sass/tree/node.rb:151:in `each' org/jruby/RubyEnumerable.java:490:in `grep' /Applications/Scout.app/Contents/Resources/vendor/gems/gems/sass-3.2.1/lib/sass/plugin/staleness_checker.rb:169:in `compute_dependencies' /Applications/Scout.app/Contents/Resources/vendor/gems/gems/sass-3.2.1/lib/sass/plugin/staleness_checker.rb:146:in `dependencies' /Applications/Scout.app/Contents/Resources/vendor/gems/gems/sass-3.2.1/lib/sass/plugin/staleness_checker.rb:123:in `dependencies_stale?' /Applications/Scout.app/Contents/Resources/vendor/gems/gems/sass-3.2.1/lib/sass/plugin/staleness_checker.rb:159:in `dependency_updated?' /Applications/Scout.app/Contents/Resources/vendor/gems/gems/sass-3.2.1/lib/sass/plugin/staleness_checker.rb:156:in `dependency_updated?' org/jruby/RubyProc.java:268:in `call' org/jruby/RubyProc.java:228:in `call' /Applications/Scout.app/Contents/Resources/vendor/gems/gems/sass-3.2.1/lib/sass/plugin/staleness_checker.rb:79:in `stylesheet_modified_since?' /Applications/Scout.app/Contents/Resources/vendor/gems/gems/sass-3.2.1/lib/sass/plugin/staleness_checker.rb:67:in `stylesheet_needs_update?' /Applications/Scout.app/Contents/Resources/vendor/gems/gems/compass-0.12.2/lib/compass/compiler.rb:67:in `needs_update?' /Applications/Scout.app/Contents/Resources/vendor/gems/gems/compass-0.12.2/lib/compass/compiler.rb:149:in `should_compile?' /Applications/Scout.app/Contents/Resources/vendor/gems/gems/compass-0.12.2/lib/compass/compiler.rb:117:in `compile_if_required' /Applications/Scout.app/Contents/Resources/vendor/gems/gems/compass-0.12.2/lib/compass/compiler.rb:103:in `run' org/jruby/RubyArray.java:1603:in `each' /Applications/Scout.app/Contents/Resources/vendor/gems/gems/compass-0.12.2/lib/compass/compiler.rb:101:in `run' /Applications/Scout.app/Contents/Resources/vendor/gems/gems/compass-0.12.2/lib/compass/compiler.rb:126:in `timed' /Applications/Scout.app/Contents/Resources/vendor/gems/gems/compass-0.12.2/lib/compass/compiler.rb:100:in `run' /Applications/Scout.app/Contents/Resources/vendor/gems/gems/compass-0.12.2/lib/compass/commands/watch_project.rb:147:in `recompile' /Applications/Scout.app/Contents/Resources/vendor/gems/gems/compass-0.12.2/lib/compass/commands/watch_project.rb:68:in `perform' /Applications/Scout.app/Contents/Resources/vendor/gems/gems/compass-0.12.2/lib/compass/commands/base.rb:18:in `execute' /Applications/Scout.app/Contents/Resources/vendor/gems/gems/compass-0.12.2/lib/compass/commands/project_base.rb:19:in `execute' /Applications/Scout.app/Contents/Resources/vendor/gems/gems/compass-0.12.2/lib/compass/exec/sub_command_ui.rb:43:in `perform!' /Applications/Scout.app/Contents/Resources/vendor/gems/gems/compass-0.12.2/lib/compass/exec/sub_command_ui.rb:15:in `run!' /Applications/Scout.app/Contents/Resources/bin/compass:12:in `(root)' 
```

**Comment by TheJaredWilcurt** [comment]
Scout-App 2 is Node based and since Compass only runs on Ruby, the new version only supports Compass Mixins. Sprite mapping is no longer available.

* [Scout-App.io](http://Scout-App.io)

Closing issue as "will not fix".
